apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tftpd
  name: tftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tftpd
  template:
    metadata:
      labels:
        app: tftpd
    spec:
      containers:
      - image:  busybox
        command:
          - udpsvd
        args: ["-Ev", "0.0.0.0",  "69", "tftpd", "/var/lib/tftpboot/"]
        imagePullPolicy: IfNotPresent
        name: tftpd
        volumeMounts:
        - mountPath: /var/lib/tftpboot/
          name: tftpboot
      nodeSelector:
        kubernetes.io/arch: arm
#    kubernetes.io/arch: amd64
      restartPolicy: Always
      volumes:
      - name: tftpboot
        nfs:
          path: /mnt/nfs/pvdata/tftpboot
          server: nfs.home
